### ISSUE TITLE
If you get rid of the cheesy social media links, I will CONSIDER adding your MEASLY code to our project

### ISSUE THREAD

**Issue by chrkahn** [Doplgamer/CSClub-Scoreboard#3]
If you get rid of the cheesy social media links, I will CONSIDER adding your MEASLY code to our project

_Originally posted by @Doplgamer in https://github.com/Doplgamer/CSClub-Scoreboard/issues/2#issuecomment-1493212746_

**Comment by Doplgamer** [comment]
Hmm, closed.
